### ISSUE TITLE
Why not using DFA inductor?

### ISSUE THREAD

**Issue by alexeyignatiev** [mvcisback/dfa-identify#5]
Hi Marcell,

It's not really an issue. I just wonder why don't you use our [later tool](https://github.com/ctlab/DFA-Inductor-py/)? It should be [better](https://alexeyignatiev.github.io/assets/pdf/zmiums-lata19-preprint.pdf) than both of the approaches you currently consider. :)

Best,
Alexey

**Comment by mvcisback** [comment]
Hi Alexey,

Nice to hear from you. To be honest, the primary reason was that I am not 100% caught of on the state-of-the-art and started the repo as a way to understand for myself - and get a baseline that I understand along the way :)

That said, there are four more practical reasons:

1. For another project, we are slightly adapting the encoding to support another form of data and using this as a starting point.
2. I actually thought the repo was just for the initial BFS-based symmetry predicates.
3. (perhaps without merit) I didn't see any documentation on how to actually use the code :)
4. (also perhaps without merit) I wanted a library that supported arbitrary sequence of hashable python objects for examples.

That said, your comment has renewed my curiosity on the tool and I will be sure to look! I particularly want to understand *why* the new implementation is better and will look at the paper as soon as I get a chance.

- Marcell

**Comment by alexeyignatiev** [comment]
Hi Marcell,

Sure, I understand that. :) I believe the tool should represent the newest approach published at LATA'19. I am sure @IZakirzyanov will be happy to answer your questions about the details of the approach. :)

Alexey

**Comment by mvcisback** [comment]
@IZakirzyanov @alexeyignatiev I finally got some time to take a look at the paper. It's nice to see such a significant improvement!

Is there an ablation study on the additional BFS constraints vs the new encoding, etc?

There's a lot of new constraints added but my understanding is that many of them are compatible with older encodings.

**Comment by mvcisback** [comment]
I guess concretely, should I be expecting that the BFS symmetry breaking(without the additional constraints to reduce the search space) should provide performance akin to DFA-Inductor. Where as using the compact encoding + the additional BFS search space reduction constraints will give DFA-Inductor2 performance?

**Comment by alexeyignatiev** [comment]
@mvcisback, I would assume so, yes. But @IZakirzyanov was the developer in the project and he should be able to properly answer your questions. So let's wait for his reply. :)

**Comment by mvcisback** [comment]
Sounds good. I will close this issue, but feel free to continue discussing.

I've also added a pointer to your library in the README

**Comment by IZakirzyanov** [comment]
@alexeyignatiev thank you for pinging! 

Hi Marcell @mvcisback! I'm not working on this project anymore, but I will be glad to answer any questions you have about the tool, approach or our paper. It is nice to know that the research continues!

> I believe the tool should represent the newest approach published at LATA'19.

I confirm that the tool represents the newest approach published at LATA'19 as well, as the initial BFS-based predicates.

> Is there an ablation study on the additional BFS constraints vs the new encoding, etc?

If I understand correctly what an ablation study is, then it was planned but no, I didn't managed to conduct that. 

> There's a lot of new constraints added but my understanding is that many of them are compatible with older encodings.

Yes, all new constraints are compatible with the elder ones.

> I guess concretely, should I be expecting that the BFS symmetry breaking(without the additional constraints to reduce the search space) should provide performance akin to DFA-Inductor. Where as using the compact encoding + the additional BFS search space reduction constraints will give DFA-Inductor2 performance?

This is correct.
